framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: ~
            messenger.bus.command: ~
            messenger.bus.event: ~

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            command:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'command_exchange'
                    queues:
                        command:
                            binding_keys: [ 'command_key' ]
            event:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'event_exchange'
                    queues:
                        event:
                            binding_keys: [ 'event_key' ]

        routing:
            # Route your messages to the transports
            'App\Shared\Application\Command\CommandInterface': command
            'App\Shared\Domain\Event\EventInterface': event

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
