security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\User\Domain\User: 'auto'
        App\User\Infrastructure\Security\SecurityUser: 'auto'

    providers:
        custom_provider:
            id: App\User\Infrastructure\Security\SecurityUserProvider

    firewalls:
        login:
            pattern: ^/api/auth/(login|token/refresh)
            stateless: true
            json_login:
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            refresh_jwt:
                check_path: /api/auth/token/refresh
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            logout:
